/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Activity {
  'id' : string,
  'isPredefined' : boolean,
  'name' : string,
  'createdAt' : Timestamp,
  'emoji' : string,
  'reminderTime' : [] | [string],
}
export interface ActivityStats {
  'manualBreaks' : bigint,
  'totalDays' : bigint,
  'freezesUsed' : bigint,
  'autoBreaks' : bigint,
  'longestStreak' : bigint,
  'currentStreak' : bigint,
}
export interface BreakLog {
  'id' : string,
  'breakDate' : string,
  'createdAt' : Timestamp,
  'wasManual' : boolean,
  'activityId' : string,
  'streakLengthAtBreak' : bigint,
  'reason' : string,
}
export interface CompleteResult {
  'isFreezeEarned' : boolean,
  'streak' : bigint,
  'milestoneDay' : [] | [bigint],
  'isNewMilestone' : boolean,
}
export interface DailyCompletion {
  'completedAt' : Timestamp,
  'date' : string,
  'activityId' : string,
}
export interface FreezeResult { 'message' : string, 'success' : boolean }
export interface FreezeStatus {
  'freezeActive' : boolean,
  'freezeDate' : [] | [string],
  'tokensAvailable' : bigint,
}
export interface MilestoneUnlock {
  'unlockedAt' : Timestamp,
  'activityId' : string,
  'milestoneDay' : bigint,
}
export interface SavedQuote { 'quoteId' : string, 'savedAt' : Timestamp }
export interface StreakPublic {
  'freezeActiveDate' : [] | [string],
  'lastCompletedDate' : [] | [string],
  'freezeTokensEarned' : bigint,
  'activityId' : string,
  'freezeTokensUsed' : bigint,
  'totalDaysCompleted' : bigint,
  'longestStreak' : bigint,
  'currentStreak' : bigint,
}
export type Timestamp = bigint;
export interface UserProfilePublic {
  'name' : string,
  'createdAt' : Timestamp,
  'onboardingComplete' : boolean,
}
export interface _SERVICE {
  'addActivity' : ActorMethod<[string, string, [] | [string]], Activity>,
  'applyFreezeToken' : ActorMethod<[string, string], FreezeResult>,
  'completeActivity' : ActorMethod<[string, string], CompleteResult>,
  'getActivities' : ActorMethod<[], Array<Activity>>,
  'getActivityStats' : ActorMethod<[string], ActivityStats>,
  'getAllBreakLogs' : ActorMethod<[], Array<BreakLog>>,
  'getAllMilestones' : ActorMethod<[], Array<[string, Array<MilestoneUnlock>]>>,
  'getAllStreaks' : ActorMethod<[], Array<[string, StreakPublic]>>,
  'getBreakLogs' : ActorMethod<[string], Array<BreakLog>>,
  'getCompletionsForMonth' : ActorMethod<
    [string, string],
    Array<DailyCompletion>
  >,
  'getFreezeStatus' : ActorMethod<[string], FreezeStatus>,
  'getSavedQuotes' : ActorMethod<[], Array<SavedQuote>>,
  'getStreakInfo' : ActorMethod<[string], [] | [StreakPublic]>,
  'getUnlockedMilestones' : ActorMethod<[string], Array<MilestoneUnlock>>,
  'getUserProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'initializeDefaultActivities' : ActorMethod<[], undefined>,
  'isCompletedToday' : ActorMethod<[string, string], boolean>,
  'recordBreak' : ActorMethod<
    [string, string, boolean, bigint, string],
    BreakLog
  >,
  'removeActivity' : ActorMethod<[string], boolean>,
  'saveQuote' : ActorMethod<[string], undefined>,
  'setUserProfile' : ActorMethod<[string], undefined>,
  'unsaveQuote' : ActorMethod<[string], undefined>,
  'updateActivityReminder' : ActorMethod<[string, [] | [string]], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];