/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const Activity = IDL.Record({
  'id' : IDL.Text,
  'isPredefined' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'emoji' : IDL.Text,
  'reminderTime' : IDL.Opt(IDL.Text),
});
export const FreezeResult = IDL.Record({
  'message' : IDL.Text,
  'success' : IDL.Bool,
});
export const CompleteResult = IDL.Record({
  'isFreezeEarned' : IDL.Bool,
  'streak' : IDL.Nat,
  'milestoneDay' : IDL.Opt(IDL.Nat),
  'isNewMilestone' : IDL.Bool,
});
export const ActivityStats = IDL.Record({
  'manualBreaks' : IDL.Nat,
  'totalDays' : IDL.Nat,
  'freezesUsed' : IDL.Nat,
  'autoBreaks' : IDL.Nat,
  'longestStreak' : IDL.Nat,
  'currentStreak' : IDL.Nat,
});
export const BreakLog = IDL.Record({
  'id' : IDL.Text,
  'breakDate' : IDL.Text,
  'createdAt' : Timestamp,
  'wasManual' : IDL.Bool,
  'activityId' : IDL.Text,
  'streakLengthAtBreak' : IDL.Nat,
  'reason' : IDL.Text,
});
export const MilestoneUnlock = IDL.Record({
  'unlockedAt' : Timestamp,
  'activityId' : IDL.Text,
  'milestoneDay' : IDL.Nat,
});
export const StreakPublic = IDL.Record({
  'freezeActiveDate' : IDL.Opt(IDL.Text),
  'lastCompletedDate' : IDL.Opt(IDL.Text),
  'freezeTokensEarned' : IDL.Nat,
  'activityId' : IDL.Text,
  'freezeTokensUsed' : IDL.Nat,
  'totalDaysCompleted' : IDL.Nat,
  'longestStreak' : IDL.Nat,
  'currentStreak' : IDL.Nat,
});
export const DailyCompletion = IDL.Record({
  'completedAt' : Timestamp,
  'date' : IDL.Text,
  'activityId' : IDL.Text,
});
export const FreezeStatus = IDL.Record({
  'freezeActive' : IDL.Bool,
  'freezeDate' : IDL.Opt(IDL.Text),
  'tokensAvailable' : IDL.Nat,
});
export const SavedQuote = IDL.Record({
  'quoteId' : IDL.Text,
  'savedAt' : Timestamp,
});
export const UserProfilePublic = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'onboardingComplete' : IDL.Bool,
});

export const idlService = IDL.Service({
  'addActivity' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [Activity],
      [],
    ),
  'applyFreezeToken' : IDL.Func([IDL.Text, IDL.Text], [FreezeResult], []),
  'completeActivity' : IDL.Func([IDL.Text, IDL.Text], [CompleteResult], []),
  'getActivities' : IDL.Func([], [IDL.Vec(Activity)], []),
  'getActivityStats' : IDL.Func([IDL.Text], [ActivityStats], []),
  'getAllBreakLogs' : IDL.Func([], [IDL.Vec(BreakLog)], []),
  'getAllMilestones' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(MilestoneUnlock)))],
      [],
    ),
  'getAllStreaks' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, StreakPublic))],
      [],
    ),
  'getBreakLogs' : IDL.Func([IDL.Text], [IDL.Vec(BreakLog)], []),
  'getCompletionsForMonth' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(DailyCompletion)],
      [],
    ),
  'getFreezeStatus' : IDL.Func([IDL.Text], [FreezeStatus], []),
  'getSavedQuotes' : IDL.Func([], [IDL.Vec(SavedQuote)], []),
  'getStreakInfo' : IDL.Func([IDL.Text], [IDL.Opt(StreakPublic)], []),
  'getUnlockedMilestones' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MilestoneUnlock)],
      [],
    ),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], []),
  'initializeDefaultActivities' : IDL.Func([], [], []),
  'isCompletedToday' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'recordBreak' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Bool, IDL.Nat, IDL.Text],
      [BreakLog],
      [],
    ),
  'removeActivity' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'saveQuote' : IDL.Func([IDL.Text], [], []),
  'setUserProfile' : IDL.Func([IDL.Text], [], []),
  'unsaveQuote' : IDL.Func([IDL.Text], [], []),
  'updateActivityReminder' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const Activity = IDL.Record({
    'id' : IDL.Text,
    'isPredefined' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'emoji' : IDL.Text,
    'reminderTime' : IDL.Opt(IDL.Text),
  });
  const FreezeResult = IDL.Record({
    'message' : IDL.Text,
    'success' : IDL.Bool,
  });
  const CompleteResult = IDL.Record({
    'isFreezeEarned' : IDL.Bool,
    'streak' : IDL.Nat,
    'milestoneDay' : IDL.Opt(IDL.Nat),
    'isNewMilestone' : IDL.Bool,
  });
  const ActivityStats = IDL.Record({
    'manualBreaks' : IDL.Nat,
    'totalDays' : IDL.Nat,
    'freezesUsed' : IDL.Nat,
    'autoBreaks' : IDL.Nat,
    'longestStreak' : IDL.Nat,
    'currentStreak' : IDL.Nat,
  });
  const BreakLog = IDL.Record({
    'id' : IDL.Text,
    'breakDate' : IDL.Text,
    'createdAt' : Timestamp,
    'wasManual' : IDL.Bool,
    'activityId' : IDL.Text,
    'streakLengthAtBreak' : IDL.Nat,
    'reason' : IDL.Text,
  });
  const MilestoneUnlock = IDL.Record({
    'unlockedAt' : Timestamp,
    'activityId' : IDL.Text,
    'milestoneDay' : IDL.Nat,
  });
  const StreakPublic = IDL.Record({
    'freezeActiveDate' : IDL.Opt(IDL.Text),
    'lastCompletedDate' : IDL.Opt(IDL.Text),
    'freezeTokensEarned' : IDL.Nat,
    'activityId' : IDL.Text,
    'freezeTokensUsed' : IDL.Nat,
    'totalDaysCompleted' : IDL.Nat,
    'longestStreak' : IDL.Nat,
    'currentStreak' : IDL.Nat,
  });
  const DailyCompletion = IDL.Record({
    'completedAt' : Timestamp,
    'date' : IDL.Text,
    'activityId' : IDL.Text,
  });
  const FreezeStatus = IDL.Record({
    'freezeActive' : IDL.Bool,
    'freezeDate' : IDL.Opt(IDL.Text),
    'tokensAvailable' : IDL.Nat,
  });
  const SavedQuote = IDL.Record({
    'quoteId' : IDL.Text,
    'savedAt' : Timestamp,
  });
  const UserProfilePublic = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'onboardingComplete' : IDL.Bool,
  });
  
  return IDL.Service({
    'addActivity' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [Activity],
        [],
      ),
    'applyFreezeToken' : IDL.Func([IDL.Text, IDL.Text], [FreezeResult], []),
    'completeActivity' : IDL.Func([IDL.Text, IDL.Text], [CompleteResult], []),
    'getActivities' : IDL.Func([], [IDL.Vec(Activity)], []),
    'getActivityStats' : IDL.Func([IDL.Text], [ActivityStats], []),
    'getAllBreakLogs' : IDL.Func([], [IDL.Vec(BreakLog)], []),
    'getAllMilestones' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(MilestoneUnlock)))],
        [],
      ),
    'getAllStreaks' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, StreakPublic))],
        [],
      ),
    'getBreakLogs' : IDL.Func([IDL.Text], [IDL.Vec(BreakLog)], []),
    'getCompletionsForMonth' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(DailyCompletion)],
        [],
      ),
    'getFreezeStatus' : IDL.Func([IDL.Text], [FreezeStatus], []),
    'getSavedQuotes' : IDL.Func([], [IDL.Vec(SavedQuote)], []),
    'getStreakInfo' : IDL.Func([IDL.Text], [IDL.Opt(StreakPublic)], []),
    'getUnlockedMilestones' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MilestoneUnlock)],
        [],
      ),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], []),
    'initializeDefaultActivities' : IDL.Func([], [], []),
    'isCompletedToday' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'recordBreak' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool, IDL.Nat, IDL.Text],
        [BreakLog],
        [],
      ),
    'removeActivity' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'saveQuote' : IDL.Func([IDL.Text], [], []),
    'setUserProfile' : IDL.Func([IDL.Text], [], []),
    'unsaveQuote' : IDL.Func([IDL.Text], [], []),
    'updateActivityReminder' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };